//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADTeam4EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjustment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adjustment()
        {
            this.AdjustmentDetails = new HashSet<AdjustmentDetail>();
        }
    
        public int AdjustmentID { get; set; }
        public string AdjustmentStatus { get; set; }
        public Nullable<int> AdjustedByEmployeeID { get; set; }
        public Nullable<int> ApprovedByEmployeeID { get; set; }
        public Nullable<System.DateTime> RequestAdjustmentDate { get; set; }
        public Nullable<System.DateTime> ApproveAdjustmentDate { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdjustmentDetail> AdjustmentDetails { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
