//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADTeam4EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjustmentDetail
    {
        public int AdjustmentDetailID { get; set; }
        public string ItemID { get; set; }
        public Nullable<int> AdjustmentID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string AdjustmentRemark { get; set; }
    
        public virtual Adjustment Adjustment { get; set; }
        public virtual Item Item { get; set; }
    }
}
