//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADTeam4EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control
    {
        public string Prefix { get; set; }
        public string Length { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    }
}
