//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADTeam4EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ADProjectSA40Team4Entities : DbContext
    {
        public ADProjectSA40Team4Entities()
            : base("name=ADProjectSA40Team4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adjustment> Adjustments { get; set; }
        public virtual DbSet<AdjustmentDetail> AdjustmentDetails { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CollectionPoint> CollectionPoints { get; set; }
        public virtual DbSet<Control> Controls { get; set; }
        public virtual DbSet<DelicatedInfo> DelicatedInfoes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<RequestDetail> RequestDetails { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SupplyItem> SupplyItems { get; set; }
        public virtual DbSet<ApproveRejectRequest_View> ApproveRejectRequest_View { get; set; }
        public virtual DbSet<DisplayLowLevelStock_View> DisplayLowLevelStock_View { get; set; }
        public virtual DbSet<DISTINCTEMPLOYEE_VIEW> DISTINCTEMPLOYEE_VIEW { get; set; }
        public virtual DbSet<RaiseAdjustmentVoucher_View> RaiseAdjustmentVoucher_View { get; set; }
        public virtual DbSet<ReorderReport_View> ReorderReport_View { get; set; }
        public virtual DbSet<RequestHistory_View> RequestHistory_View { get; set; }
        public virtual DbSet<RequestReport_View> RequestReport_View { get; set; }
    }
}
