//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADTeam4EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestReport_View
    {
        public int RequestID { get; set; }
        public string DepartmentName { get; set; }
        public string CategoryName { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
        public Nullable<int> Total_Quantity { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
    }
}
